teraslice-test-harness downloads and includes external assets
terascope/teraslice pull request #2288
Opened 2020-10-27 18:02 UTC by ciorg

* downloads github stored assets to ./test/.cache/assets
* incorporates dowloaded assets into the test assets directory
* added tests for downloadExternalAsset
* updated documentation
* bumped to v0.27.0

2020-10-27 20:26 UTC, peterdemartini requested changes

2020-10-27 20:26 UTC, peterdemartini commented on packages/teraslice-test-harness/src/utils.ts
> +        return path.join(__dirname.slice(0, __dirname.indexOf('node_modules')), 'test', '.cache');
What does this do?

2020-10-27 20:26 UTC, peterdemartini commented on packages/teraslice-test-harness/src/download-external-asset.ts
> +            return (release: any) => release.tag_name.includes(version);
If the tag name was 'v1.2.10' and the version is 'v1.2.1', it would match when it shouldn't have.

2020-10-27 20:26 UTC, peterdemartini commented on packages/teraslice-test-harness/src/download-external-asset.ts
> +            const result = downloadRelease(
```suggestion
            const result = await downloadRelease(
```

2020-10-27 21:00 UTC, ciorg commented on packages/teraslice-test-harness/src/utils.ts
> +        return path.join(__dirname.slice(0, __dirname.indexOf('node_modules')), 'test', '.cache');
Function to get the path to the .cache  directory.

The test dir is in the same dir as the node_modules, so it gets the path to that level, then adds the 'test/.cache'.  Except when it is itself being tested then that method can't be used to find the test directory.

2020-10-27 21:02 UTC, ciorg commented on packages/teraslice-test-harness/src/download-external-asset.ts
> +            return (release: any) => release.tag_name.includes(version);
good point

2020-10-27 21:02 UTC, ciorg commented on packages/teraslice-test-harness/src/download-external-asset.ts
> +            const result = downloadRelease(
yeah

2020-10-27 21:27 UTC, peterdemartini requested changes

2020-10-27 21:27 UTC, peterdemartini commented on packages/teraslice-test-harness/src/utils.ts
> +        return path.join(__dirname.slice(0, __dirname.indexOf('node_modules')), 'test', '.cache');
That won't work with some module setups (like in a monorepo), I think using `path.resolve('./test/.cache')` would be sufficient?

2020-10-27 21:41 UTC, ciorg commented on packages/teraslice-test-harness/src/utils.ts
> +        return path.join(__dirname.slice(0, __dirname.indexOf('node_modules')), 'test', '.cache');
except path.resolve won't work if it's the first time it's ran, because .cache doesn't exist yet.

2020-10-27 22:07 UTC, ciorg commented on packages/teraslice-test-harness/src/utils.ts
> +        return path.join(__dirname.slice(0, __dirname.indexOf('node_modules')), 'test', '.cache');
maybe it's just better to use the .teraslice dir

2020-10-28 01:19 UTC, peterdemartini commented
LGTM, don't forget to bumper

2020-10-28 14:29 UTC, peterdemartini approved these changes

2020-10-28 15:50 UTC, merged