data-mate/ utils string functions
terascope/teraslice pull request #2676
Opened 2021-04-28 23:33 UTC by ciorg

* isPort
* isMimeType
* isISDN
* isPhoneNumberLIke
* isPostolCode
* isAlphaNumeric

2021-04-29 14:45 UTC, peterdemartini commented on packages/data-mate/src/function-configs/string/isMimeType.ts
> +    name: 'isMimeType',
Shouldn't this be `isMIMEType`?

2021-04-29 14:45 UTC, peterdemartini commented on packages/data-mate/src/function-configs/string/isMimeType.ts
> +    description: 'Checks to see if input is a MIME Type',
This description doesn't give you any more value than the function itself. Maybe describe what MIME is?

2021-04-29 14:45 UTC, peterdemartini commented on packages/data-mate/src/function-configs/string/isMimeType.ts
> +    accepts: [],
This should probably only accept strings since this could be optimized out if given anything else
```suggestion
    accepts: [FieldType.String],
```

2021-04-29 14:45 UTC, peterdemartini commented on packages/utils/src/phone-number.ts
> +export function isPhoneNumberLike(input: unknown): boolean {
What is the benefit of this function? It seems extremely loose?

2021-04-29 17:02 UTC, ciorg commented on packages/utils/src/phone-number.ts
> +export function isPhoneNumberLike(input: unknown): boolean {
It is extremely loose, the problem is the isISDN assumes everything is in an international phone number format and throws out a lot of possibly good phone numbers. 

If a country is provided along with a number to the ISDN it becomes much more reliable, and thinking about this the country needs to be an optional arg for the isISDN function.  

But in enough cases the data didn't have accurate country info and isISDN was rejecting most of the phone number values, so the isPhoneNumber like function was created.  A basic check based on number of  digits, min and max for a valid phone number.

2021-04-29 20:41 UTC, ciorg commented on packages/data-mate/src/function-configs/string/isMimeType.ts
> +    accepts: [],
fixed this with latest commit

2021-04-29 20:41 UTC, ciorg commented on packages/data-mate/src/function-configs/string/isMimeType.ts
> +    name: 'isMimeType',
fixed this with latest commit

2021-04-29 21:00 UTC, ciorg commented on packages/data-mate/src/function-configs/string/isMimeType.ts
> +    description: 'Checks to see if input is a MIME Type',
I added more details to the description

2021-04-29 21:04 UTC, ciorg commented
Had a strange issue where I changed the file isMimeType -> isMIMEType and was causing an error on the build saying it couldn't find the isMIMEType file for the CI tests.  It built fine locally, but I changed the file name back to isMimeType and it passed.  Not sure  whats going on there.

2021-04-29 23:15 UTC, peterdemartini commented
That's because macos file system is case insensitive by default. You need to use `git mv` to tell git the file was moved. You might need to rename it back and then use the `git mv` command.

2021-05-03 17:40 UTC, peterdemartini commented on packages/data-mate/src/function-configs/string/isAlphaNumeric.ts
> +        if (!isString(locale) || !('this' in validator.isAlphanumericLocales)) {
```suggestion
        if (!isString(locale) || !(locale in validator.isAlphanumericLocales)) {
```

2021-05-03 17:41 UTC, peterdemartini commented
This needs to be updated from master, also we should be writing examples (a lot of the spec files you created can be deleted)

2021-05-03 17:41 UTC, peterdemartini commented on packages/utils/src/phone-number.ts
> +export function isPhoneNumberLike(input: unknown): boolean {
We should probably have that described in jsdoc

2021-05-03 21:08 UTC, peterdemartini approved these changes

2021-05-03 21:18 UTC, jsnoble requested changes
Is there a new reason for the styling changes

2021-05-03 21:18 UTC, jsnoble commented on packages/data-mate/src/function-configs/string/isBase64.ts
> +        FieldType.String
does this need to be on a new line?

2021-05-03 21:18 UTC, jsnoble commented on packages/data-mate/src/function-configs/string/isCountryCode.ts
> +        FieldType.String
does this need to be on a new line?

2021-05-03 21:18 UTC, jsnoble commented on packages/data-mate/src/function-configs/string/isEmail.ts
> +        FieldType.String
does this need to be on a new line?

2021-05-03 21:18 UTC, jsnoble commented on packages/data-mate/src/function-configs/string/isFQDN.ts
> +        FieldType.String
does this need to be on a new line?

2021-05-03 21:28 UTC, jsnoble approved these changes
LTGM

2021-05-03 21:39 UTC, merged