add support for JS asset bundle refs: 2748
terascope/teraslice pull request #2751
Opened 2021-05-25 23:36 UTC by godber

This implements the JS asset build.

2021-05-25 23:36 UTC, godber commented
refs: https://github.com/terascope/teraslice/issues/2748

2021-05-25 23:39 UTC, godber commented
Please note my FIXME comment.

I think we should just require the `entryPoint` for both JS and TypeScript.  Alternatively, we can assume a specific path for JS.  Regardless, we should do one or the other, not both under different conditions.  I'd be happy to go back and add the entryPoints to the public assets.

2021-05-25 23:41 UTC, godber commented
On drawback of this whole static registry thing is that asset developers can write assets, which include passing unit tests, that still fail to include processors because they have forgotten to include them in the registry.

2021-05-26 17:55 UTC, godber commented
> Please note my FIXME comment.
> 
> I think we should just require the `entryPoint` for both JS and TypeScript. Alternatively, we can assume a specific path for JS. Regardless, we should do one or the other, not both under different conditions. I'd be happy to go back and add the entryPoints to the public assets.

After thinking overnight, I think that since we are now requiring that asset registries be implemented we can easily extend that requirement as follows ...

"All assets must implement registries that provide a single entrypoint to all of the processors/functionality contained in that asset.  If the asset is implemented in Javascript, that registry must be `asset/index.js` and if the asset is implemented in TypeScript, the registry must be `asset/src/index.ts`."

If we require this, then we can make the assumption that one of those index files will be present.  We can eliminate the `entryPoint` (or `srcMain`) property in the `package.json`.

This is what I will do.

2021-05-27 23:55 UTC, godber commented
I haven't run bump yet, but I think this is ready.

2021-05-28 14:53 UTC, peterdemartini requested changes
This looks good for the most part, there are a couple log messages (one was previously already there) but I think they could be improved by not including the tmp directory since it makes it more difficult to understand.

<img width="1440" alt="Screen Shot 2021-05-28 at 7 49 09 AM" src="https://user-images.githubusercontent.com/1044698/120002240-7805c180-bf89-11eb-9324-0ad022a478d6.png">

2021-05-28 14:53 UTC, peterdemartini commented on packages/teraslice-cli/src/helpers/asset-src.ts
> +                    entryPoint = require.resolve(path.join(tmpDir.name, 'asset', 'index.js'));
This doesn't need to be changed but `path.join` should be sufficient and `require.resolve` does not add any value here.

2021-05-28 15:44 UTC, godber commented on packages/teraslice-cli/src/helpers/asset-src.ts
> +                    entryPoint = require.resolve(path.join(tmpDir.name, 'asset', 'index.js'));
The main point of the logs is to provide the temp directory just in case something goes wrong the user can find the temp directories and hopefully track down the problem.  If I removed the temp directories the logs would always be one of two possibilities:

```
* entryPoint: asset/src/index.ts
* doing a test require of index.js
```

or


```
* entryPoint: asset/index.js
* doing a test require of index.js
```

2021-05-28 15:52 UTC, peterdemartini commented on packages/teraslice-cli/src/helpers/asset-src.ts
> +                    entryPoint = require.resolve(path.join(tmpDir.name, 'asset', 'index.js'));
The entryPoint line is more clear without the temp directory and the temp directory doesn't add any value there. The require test line is maybe a different story, I personally think it would be better to output the asset registry, if the require test fails it should definitely output the full file path so it can be debugged

2021-05-28 16:09 UTC, godber commented on packages/teraslice-cli/src/helpers/asset-src.ts
> +                    entryPoint = require.resolve(path.join(tmpDir.name, 'asset', 'index.js'));
Yeah, let me remove that and confirm it still works.

2021-05-28 17:07 UTC, peterdemartini approved these changes

2021-05-28 18:24 UTC, merged