Dynamic arg support
terascope/teraslice pull request #2760
Opened 2021-05-27 22:27 UTC by jsnoble

- allow dynamic arg generation by specifying args as a function
- moved arg type interfaces so that they can be exported

2021-05-27 22:41 UTC, peterdemartini commented on packages/data-mate/src/adapters/data-frame-adapter/index.ts
> +    args?: T | ((index: number, column: Column<unknown>) => T),
I am not sure if we want to just have column here, it would be more useful to have the whole data frame if available. For our use case though, we probably won't even need this argument.

2021-05-27 22:41 UTC, peterdemartini commented on packages/data-mate/src/adapters/function-adapter/interfaces.ts
> +    readonly args?: T | ((index: number, column: unknown[]) => T),
I am not sure if we want to just have column here, it would be more useful to have the whole data frame if available. For our use case though, we probably won't even need this argument.

2021-05-28 17:45 UTC, ciorg approved these changes
LGTM

sorry you had to move all those small interfaces!

2021-05-28 17:52 UTC, peterdemartini requested changes

2021-05-28 17:52 UTC, peterdemartini commented on packages/data-mate/src/function-configs/interfaces.ts
> +export interface FormatDateArgs {
Lets either move these arg definitions to a different interfaces file or export them from the individual function files using:

`export { FormatDateArgs } from './formatDate';`

2021-06-08 20:39 UTC, peterdemartini commented on packages/utils/src/ip.ts
> +    const ipValue = primitiveToString(input);
I don't think we want to call this here

2021-06-08 20:39 UTC, peterdemartini commented on packages/utils/src/ip.ts
> +export function isIP(input: unknown): input is FieldType.IP {
```suggestion
export function isIP(input: unknown): input is string {
```

2021-06-08 20:39 UTC, peterdemartini commented on packages/utils/src/ip.ts
> +export function isIPOrThrow(input: unknown): FieldType.IP {
```suggestion
export function isIPOrThrow(input: unknown): string {
```

2021-06-08 21:47 UTC, peterdemartini requested changes

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/adapters/argument-validator/index.ts
> +                const typeValidator = getValidatorForFieldType(typeConfig);
This needs to actually coerce the argument values, currently this is just used as a validator. Just to note, this should create new copy of the arguments and NOT mutate the input

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/function-configs/json/cast.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Why is this disabled here?
```suggestion
```

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/function-configs/json/cast.ts
> +        return (input: unknown) => {
This implementation should just be noop (a function that returns the input)

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/function-configs/json/cast.ts
> +    description: 'Converts the field type of the entity to another type',
```suggestion
    description: 'Converts the field to another type, this is also useful changing the metadata of field',
```

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/function-configs/json/cast.ts
> +            for (const [field, config] of Object.entries(args.child_config)) {
This should probably be validated using using a function from the data types package

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/function-configs/json/cast.ts
> +const castConfig: FieldTransformConfig<CastArgs> = {
Shouldn't this be exported? It is possible we are missing the reference to this in the index.ts file too

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/src/function-configs/json/cast.ts
> +export interface CastArgs {
```suggestion
export type CastArgs = DataTypeFieldConfig & { child_config?: DataTypeFields }
```

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/test/function-configs/dynamic-args-spec.ts
> +    // describe('with functionAdapter', () => {
We should remove the commented tests

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/test/function-configs/functionTestHarness.ts
> +        // disabling tests till we have a clearer use case
We should remove these because by the time we need this to work, the code will be out of sync what it should be and distract us from getting it done right. It would be better to use git for a record of this change

2021-06-08 21:47 UTC, peterdemartini commented on packages/data-mate/test/function-configs/geo/toGeoPoint-spec.ts
> +    // describe('when paired with fieldFunctionAdapter', () => {
We should remove the commented code

2021-06-08 21:47 UTC, peterdemartini commented on packages/utils/src/field-type.ts
> +export function isIPOrThrow(input: unknown): string {
This should be the `./ip.ts` file, and also it is missing some jsdoc

2021-06-08 21:47 UTC, peterdemartini commented on packages/utils/src/field-type.ts
> +export function coerceToType<T = unknown>(
This is missing some jsdoc

2021-06-08 21:47 UTC, peterdemartini commented on packages/utils/src/field-type.ts
> +            return (input) => input;
This would also potentially miss configurations to pass through, might be better to explicitly add a case for `FieldType.Any` and then throw in the default case to avoid a missing field type case

2021-06-08 21:47 UTC, peterdemartini commented on packages/utils/src/field-type.ts
> +            return toBigIntOrThrow;
It seems to me like `coerceToNumberType` should either be renamed to `coerceIntergerType` or be changed to handle all number types.

```suggestion
        case FieldType.Float:
        case FieldType.Number:
        case FieldType.Double:
        case FieldType.Byte:
        case FieldType.Short:
        case FieldType.Integer:
        case FieldType.Long:
            return coerceToNumberType(argFieldType.type);
```

2021-06-08 21:47 UTC, peterdemartini commented on packages/utils/src/ip.ts
> +export function isIPRangeOrThrow(input: unknown): string {
This is missing jsdoc

2021-06-09 15:16 UTC, jsnoble commented on packages/utils/src/field-type.ts
> +export function isIPOrThrow(input: unknown): string {
I first had it in the ip file, and then you stated `I don't think we want to call this here`, so I moved it back to fieldType. If your meaning was something else what was it then?

2021-06-09 15:26 UTC, peterdemartini commented on packages/utils/src/field-type.ts
> +export function isIPOrThrow(input: unknown): string {
Ahh yes, I should be more specific, I was referring to the `primitiveToString` function call since we only allow strings as input it was useless call

2021-06-09 15:52 UTC, peterdemartini requested changes
This is close, there is still the argument validator change that is needed

2021-06-09 15:52 UTC, peterdemartini commented on packages/data-mate/test/function-configs/dynamic-args-spec.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Do we need this eslint comment?

2021-06-09 22:24 UTC, peterdemartini approved these changes
Overall I think this looks good there is just one comment regarding an eslint ignore

2021-06-09 22:30 UTC, ciorg approved these changes
LGTM

2021-06-09 22:31 UTC, merged