Date tuple
terascope/teraslice pull request #2803
Opened 2021-06-09 16:43 UTC by ciorg

* added DateTuple support to date functions in utils and function-configs in data-mate and respective tests

2021-06-09 23:10 UTC, peterdemartini requested changes
This also needs to be updated from the feature branch

2021-06-09 23:10 UTC, peterdemartini commented on packages/data-mate/src/function-configs/date/getMonth.ts
> +    process_mode: ProcessMode.FULL_VALUES,
This should be `INDIVIDUAL_VALUES`

2021-06-09 23:10 UTC, peterdemartini commented on packages/data-mate/src/column/utils.ts
> +        if (containsArray && value != null) {
To support the `Any` we need this logic, since `Any` doesn't have to be any array
```suggestion
        if (containsArray && Array.isArray(value)) {
```

2021-06-09 23:10 UTC, peterdemartini commented on packages/types/src/dates.ts
> +export type DateTypes = Date | string | number | DateTuple;
Not a big fan of this name. It could also use some jsdoc describing what it is used for.

```suggestion
export type DateInputType = Date | string | number | DateTuple;
```

2021-06-10 14:51 UTC, peterdemartini approved these changes
LGTM, except I have one comment

2021-06-10 14:51 UTC, peterdemartini commented on packages/utils/src/dates.ts
> +        return getValidDateOrThrow(toISO8601(val));
Converting this to ISO8601 string is excessive work. Doing something like `new Date(input[0] + (input[1] * 60_000))` would be less work and easier to process

2021-06-10 16:19 UTC, jsnoble approved these changes
LGTM besides peters comments

2021-06-10 16:59 UTC, merged