Add asset registry generator
terascope/teraslice pull request #2810
Opened 2021-06-11 01:11 UTC by godber

This is still mostly a sketch with only bits implemented, but I think I can pull this together soon.

I am trying to dynamically generate the asset registry.

This addresses #2769

2021-06-11 01:16 UTC, godber commented
What are the names of these things:

https://github.com/terascope/file-assets/blob/master/asset/src/index.ts#L40-L49

```
export const ASSETS = {
            file_exporter: {
                Processor: FileBatcher,
                Schema: FileExporterSchema
            },
            file_reader: {
                Fetcher: FileFetcher,
                Schema: FileReaderSchema,
                Slicer: FileSlicerOperation
```

Do these things have generic names?
* `file_exporter` =?  Operation? Processor?
*  `FileBatcher` =? `FileExporterSchema` ... the things UNDER the `file_exporter` ... do they have a name?

2021-06-11 14:56 UTC, peterdemartini commented
I am not sure how to answer that but maybe a simple example will be more helpful (it will need to be changed to work with multiple operations and the files.


```ts
// NOTE toPascalCase comes from @terascope/utils
import ${toPascalCase(`${op_directory}_${op_file_name}`)} from `${op_directory}/${op_file_name}`;

export const ASSETS = {
       [op_directory]: {
            [toPascalCase(op_file_name)]:  ${toPascalCase(`${op_directory}_${op_file_name}`)},
       }
}
```

```js
// NOTE toPascalCase comes from @terascope/utils
const ${toPascalCase(`${op_directory}_${op_file_name}`)} = require(`${op_directory}/${op_file_name}`);

module.exports = {
      ASSETS: {
            [op_directory]: {
                 [toPascalCase(op_file_name)]:  ${toPascalCase(`${op_directory}_${op_file_name}`)},
            }
     }
}
```

We only care about a few select file name combinations in a operation, the easiest way for you would be to just find any file with the name `processor`, `schema`, `api`, `fetcher`, or `slicer`.

2021-06-11 14:57 UTC, peterdemartini commented
If you have any more questions we can do a call

2021-06-14 19:08 UTC, godber commented
@ciorg this is mostly functional I think ... I've only tried it on one internal asset, usage as follows:

```
node ./bin/teraslice-cli.js assets init --registry --base-dir /Users/godber/Workspace/asset_dir
```

There are a few cleanup things (console.error -> reply.foo) and a few other improvements.

Feel free to take this over and improve or just use this branch temporarily.  If nothing else, this PR serves as a good start.

2021-06-14 19:31 UTC, peterdemartini commented on packages/teraslice-cli/src/generators/new-processor/index.ts
> +            { name: capitalizeFirstLetter(camelCase(name)) });
This should just use `toPascalCase` from `@terascope/utils`

2021-06-14 19:31 UTC, peterdemartini commented on packages/teraslice-cli/package.json
> +        "lodash.set": "^4.3.2",
We shouldn't need this since this adds an extra dependency, just `set` from `@terascope/utils` which is the same thing

2021-06-16 22:18 UTC, ciorg commented
* added functionality to copy `__state_assets` dir if it's in the top level asset directory for bundled assets
* tested this  with an internal asset and job and it worked, both generating the registry and coping the static assets

2021-06-16 22:36 UTC, peterdemartini requested changes

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/generator-templates/registry/index.ejs
> +
We should disable eslint for the file:

```suggestion

/* eslint-disable */
```

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/package.json
> +        "@types/lodash.set": "^4.3.6",
We don't need this dependency

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/src/generators/registry/index.ts
> +            throw new Error(`ERROR: ${error}`);
This try catch is not adding any value

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/src/generators/registry/index.ts
> +            console.error(`ERROR: ${error}`);
Why does it do this?

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/src/helpers/asset-src.ts
> +type OpType = 'Api' | 'Fetcher' | 'Processor' | 'Schema' | 'Slicer';
```suggestion
type OpType = 'API' | 'Fetcher' | 'Processor' | 'Schema' | 'Slicer';
```

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/src/helpers/asset-src.ts
> +        return glob(matchString, { ignore: ['**/node_modules/**', '**/__lib/**'] });
```suggestion
        return glob(matchString, { ignore: ['**/node_modules/**', '**/_*/**', '**/.*/**'] });
```

2021-06-16 22:36 UTC, peterdemartini commented on packages/teraslice-cli/src/helpers/utils.ts
> +export function capitalizeFirstLetter(string: string): string {
We should remove this since it is a duplicate to `firstToUpper` in `@terascope/utils`

2021-06-17 15:12 UTC, peterdemartini reviewed
I manually tested this and this LGTM, I have a couple of minor comments that can optional be addressed

2021-06-17 15:12 UTC, peterdemartini approved these changes
Sorry I meant to approve that (with additional suggestions)

2021-06-17 15:12 UTC, peterdemartini commented
Don't forget to bump too

2021-06-21 16:47 UTC, peterdemartini commented
Don't forget to update from master before bumping

2021-06-21 20:27 UTC, godber commented on packages/teraslice-cli/src/cmds/assets/init.ts
> +                // FIXME: manually verify that this check behaves the same after my change here.
I never double checked this.  Did you verify that the other modes work as well?  e.g. `init` without `--registry`?

2021-06-21 20:33 UTC, peterdemartini commented on packages/teraslice-cli/src/cmds/assets/init.ts
> +                // FIXME: manually verify that this check behaves the same after my change here.
When testing this PR, I found https://github.com/terascope/teraslice/issues/2824. However I thought it was unrelated to these changes

2021-06-21 20:39 UTC, merged