K8s improvements summer 2021
terascope/teraslice pull request #2962
Opened 2021-08-24 00:51 UTC by godber

This PR will address the issues in the following milestone:

https://github.com/terascope/teraslice/milestone/8

2021-08-24 00:51 UTC, godber commented
Issue #2938 is the first one I've addressed.

2021-09-09 14:57 UTC, godber commented
Manually checking the `podAntiAffinity` on a pod on a running test job on a cluster where I set `    kubernetes_worker_antiaffinity: true`, I get the following:

```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - teraslice
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - ts-dev1
          topologyKey: kubernetes.io/hostname
        weight: 1
```

2021-09-09 17:12 UTC, peterdemartini requested changes
One change recommended, and also teraslice needs to be bumped

2021-09-09 17:12 UTC, peterdemartini commented on Dockerfile
> +FROM terascope/node-base:14.17.5
I think there is a `14.17.6` now.

```suggestion
FROM terascope/node-base:14.17.6
```

2021-09-09 17:34 UTC, peterdemartini approved these changes
LGTM

2021-09-09 17:53 UTC, merged