Async client creation
terascope/teraslice pull request #3254
Opened 2022-04-07 20:21 UTC by jsnoble

- base foundation to create async elasticsearch client (only enough for spaces)
- updated packages

2022-04-11 18:10 UTC, godber requested changes
We reviewed this on zoom and have requested the changes listed here as well as changing the conditionals on version to version and `distribution`.

2022-04-11 18:10 UTC, godber commented on packages/elasticsearch-store/src/elasticsearch-client/create-client.ts
> +                client_type: 'opensearch',
Change `client_type` to `distribution`.

2022-04-14 20:35 UTC, kstaken commented on packages/teraslice/lib/storage/backends/elasticsearch_store.js
> +            if (esVersion !== 6) {
Does this need to include a check on the `distribution` as well?

2022-04-14 20:37 UTC, jsnoble commented on packages/teraslice/lib/storage/backends/elasticsearch_store.js
> +            if (esVersion !== 6) {
hmm, good spot you found, is should be able to use the helper method isElasticsearch6 for this

2022-04-19 15:31 UTC, merged