cli watch option, unified logic for jobs and tjm
terascope/teraslice pull request #3385
Opened 2023-08-08 20:12 UTC by ciorg

2023-10-04 20:23 UTC, godber requested changes

2023-10-04 21:18 UTC, ciorg commented on packages/teraslice-cli/src/cmds/jobs/restart.ts
> +            .example('$0 jobs restart CLUSTER_ALIAS JOB_ID all --status failing', 'restarts all failing jobs on the cluster')
yeah - JOB_ID is a typo

2023-10-05 16:19 UTC, ciorg commented on packages/teraslice-cli/src/helpers/yargs-options.ts
> +            describe: 'Watches job for n number of slices, ensures correct number of workers and no failed slices.',
It doesn't return a value, but exits with code 1 if the watch is not successful, ie failed slices or not enough workers after n slices.

There is a timeout which defaults to 2 minutes

2023-10-05 16:37 UTC, ciorg commented on packages/teraslice-cli/src/helpers/jobs.ts
> +    async error() {
yeah - there is definitely more refinement that could be done on this front.  I'm just not sure if I want to do it now.

2023-10-05 23:39 UTC, godber commented on packages/teraslice-cli/src/helpers/yargs-options.ts
> +            describe: 'Watches job for n number of slices, ensures correct number of workers and no failed slices.',
Great!

2023-10-05 23:39 UTC, godber approved these changes

2023-10-10 22:54 UTC, merged