Upgrade Elasticsearch from version 6.5.4 to 7.9.3
terascope/teraslice pull request #3393
Opened 2023-08-30 21:01 UTC by busma13

Update docker-compose.yml file:

    Upgrade Elasticsearch from version 6.5.4 to version 7.9.3

2023-08-31 01:48 UTC, godber requested changes
Go ahead and follow the instructions on `upgrading` from 2 to 3 outlined here:

https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading

There are only a few things and even fewer of them apply to our file.

Also, when you create a PR, you should add `refs: #NNNN` to the comment where `NNNN` is the issue number it addresses, it will link the PR and the Issue.

2023-08-31 21:14 UTC, busma13 commented
Using the docker-compose.yml file from the master branch, I cannot successfully build a teraslice docker image.  It looks like the node-base:14.21.3 image is amd64 and not compatible with the arm64 architecture of my MacBook M2.

```
peterluitjens@Peters-MacBook-Pro teraslice % docker compose up -d --build
[+] Building 0.7s (5/5) FINISHED                                                                                                                              docker:desktop-linux
 => [teraslice-master internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 991B                                                                                                                                          0.0s
 => [teraslice-master internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 373B                                                                                                                                             0.0s
 => ERROR [teraslice-worker internal] load metadata for docker.io/terascope/node-base:14.21.3                                                                                 0.6s
 => [teraslice-worker internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 373B                                                                                                                                             0.0s
 => [teraslice-worker internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 991B                                                                                                                                          0.0s
------
 > [teraslice-worker internal] load metadata for docker.io/terascope/node-base:14.21.3:
------
failed to solve: terascope/node-base:14.21.3: no match for platform in manifest sha256:0869240b6214519e5ab41188d1fd9cd257822940d89ab8c1c535c506f5b628b2: not found
```

2023-09-01 03:05 UTC, busma13 commented
I was able to build multiple docker images with different architectures following these instructions:

https://docs.docker.com/build/building/multi-platform/#getting-started

This stack overflow question gives some other workarounds for architecture mismatches during docker builds:

https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos

2023-09-06 00:34 UTC, godber requested changes

2023-09-06 00:34 UTC, godber commented on docker-compose.yml
> +    platform: linux/amd64
```suggestion
    platform: linux/amd64  # platform specified to force amd64 on arm MacOS docker
```

2023-09-06 01:22 UTC, godber commented
After running `docker compose up -d --build` on my Intel Mac, I got all of these images starting OK:

```
 docker compose ps
NAME                           IMAGE                                                 COMMAND                  SERVICE             CREATED             STATUS                    PORTS
teraslice-elasticsearch-1      docker.elastic.co/elasticsearch/elasticsearch:7.9.3   "/tini -- /usr/local…"   elasticsearch       53 seconds ago      Up 51 seconds (healthy)   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
teraslice-kafka-1              terascope/kafka-zookeeper:v1.1.0                      "supervisord -n"         kafka               53 seconds ago      Up 52 seconds             0.0.0.0:2181->2181/tcp, 0.0.0.0:9092->9092/tcp
teraslice-teraslice-master-1   teraslice-teraslice-master                            "/sbin/tini -- node …"   teraslice-master    53 seconds ago      Up 52 seconds (healthy)   0.0.0.0:5678->5678/tcp
teraslice-teraslice-worker-1   teraslice-teraslice-worker                            "/sbin/tini -- node …"   teraslice-worker    53 seconds ago      Up 51 seconds (healthy)   5678/tcp
```

2023-09-06 14:15 UTC, godber approved these changes

2023-09-06 14:16 UTC, merged