add ts-scripts bump feature for assets
terascope/teraslice pull request #3408
Opened 2023-09-13 21:19 UTC by sotojn

@busma13 and I added an asset bump feature to the ```ts-scripts``` bump command.

You can now run the bump command inside the ```root``` directory of an ```asset```. 

For example here is running ```yarn bump``` inside of the root directory of ```standard assets```

```cmd
User@standard-assets-root % yarn bump                          
ts-scripts.js bump [packages..]

Update a package to specific version and its dependencies. This should be run in the root of the workspace.

Positionals:
  packages  Run scripts for one or more package (if specifying more than one make sure they are ordered by dependants)
                                                                                                                   [array] [default: []]

Options:
      --prerelease-id  Specify the prerelease identifier, defaults to RC                                                 [default: "rc"]
      --skip-reset     Skip resetting the packages to latest from NPM                                         [boolean] [default: false]
  -d, --deps           Bump the child dependencies recursively, (ignores the monorepo's main package)          [boolean] [default: true]
      --skip-asset     If in an asset repository, bump the package version without updating the asset version [boolean] [default: false]
      --patch          Bump release by patch                                                       [boolean] [required] [default: false]
      --minor          Bump release by minor                                                       [boolean] [required] [default: false]
      --major          Bump release by major                                                       [boolean] [required] [default: false]
      --prerelease     Bump release by prerelease                                                  [boolean] [required] [default: false]
      --prepatch       Bump release by prepatch                                                    [boolean] [required] [default: false]
      --preminor       Bump release by preminor                                                    [boolean] [required] [default: false]
      --premajor       Bump release by premajor                                                    [boolean] [required] [default: false]
  -r, --release        Specify the release change for the version, see https://www.npmjs.com/package/semver.
                       [DEPRECATED] Use --patch, --minor, --major, etc
                                         [string] [choices: "patch", "minor", "major", "prerelease", "prepatch", "preminor", "premajor"]
  -h, --help           Show help                                                                                               [boolean]
  -v, --version        Show version number                                                                                     [boolean]

Examples:
  ts-scripts.js bump  example // 0.20.0 => 0.20.1
  ts-scripts.js bump  --patch example // 0.20.0 => 0.20.1
  ts-scripts.js bump  --minor example // 0.5.0 => 0.6.0
  ts-scripts.js bump  --prepatch example // 0.20.0 => 0.20.1-rc.0
  ts-scripts.js bump  --premajor example // 0.15.0 => 1.0.0-rc.0
  ts-scripts.js bump  --prerelease example // 0.20.1-rc.0 => 0.20.1-rc.1

Error: Bump requires at least one of --patch, --minor, --major, --prerelease, --prepatch, --preminor, --premajor to be specified
    at getRelease (/Users/jsoto/Workspace/teraslice/packages/scripts/dist/src/cmds/bump.js:106:15)
    at Object.handler (/Users/jsoto/Workspace/teraslice/packages/scripts/dist/src/cmds/bump.js:77:25)
    at /Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:9604)
    at _.runCommand (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:7231)
    at te.[runYargsParserAndExecuteCommands] (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:58539)
    at te.parse (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:40478)
    at te.get [as argv] (/Users/jsoto/Workspace/teraslice/packages/scripts/node_modules/yargs/build/index.cjs:1:62028)
User@standard-assets-root % 
```

In this example I will be adding a patch to ```standard-assets-apis``` package using ```yarn bump standard-assets-apis --patch```

```
User@standard-assets % yarn bump standard-asset-apis  --patch 
⚠  warning   bump has detected the root directory is an Asset.
●  note      bump is in Asset mode.
⚠  warning   @terascope/standard-asset-apis is not in-sync with the remote NPM version, resetting to v0.6.1 before bumping to v0.6.2
ℹ  info      => Updated @terascope/standard-asset-apis from version 0.6.1 to 0.6.2
---> Updating prod dependency @terascope/standard-asset-apis's version of @terascope/standard-asset-apis to 0.6.2
---> Updating dev dependency @terascope/standard-asset-apis's version of @terascope/standard-asset-apis to 0.6.2
ℹ  info      => Updated Asset from version 0.22.1 to 0.22.2
⬤  debug     wrote asset/asset.json JSON file
⬤  debug     wrote asset/package.json JSON file
ℹ  info      => Updated asset.json from version 0.22.1 to 0.22.2
✔  success   

Please commit these changes:

    git commit -a -m "bump: (patch) @terascope/standard-asset-apis@0.6.2" && git push

User@standard-assets % 

````

You can add the ```--skip-asset``` flag to not update the asset version in the process.

2023-09-13 22:18 UTC, sotojn commented
Issue ref #3388

2023-09-14 10:37 UTC, godber requested changes

2023-09-14 15:11 UTC, busma13 commented on packages/scripts/src/helpers/interfaces.ts
> +    'linkToMain', 'root', 'tests', 'asset'
No. Removed.

2023-09-14 16:18 UTC, godber commented on packages/scripts/src/helpers/packages.ts
> +    workspaces = workspaces.filter((space) => space !== '.');
Question: Should we be doing this, or should we be be removing the `.` from the workspaces of the assets?  Why does this discrepancy exist?

2023-09-14 16:27 UTC, godber commented on packages/scripts/test/bump-spec.ts
> +                const path = `${process.cwd()}/asset`;
Can this be changed to use a temp directory?

2023-09-14 16:29 UTC, godber commented on packages/scripts/test/bump-spec.ts
> +                const path = `${process.cwd()}/asset`;
https://nodejs.org/docs/latest-v18.x/api/fs.html#fspromisesmkdtempprefix-options

2023-09-18 15:38 UTC, busma13 commented on docs/packages/test-pkg/overview.md
> +---
Removed.

2023-09-18 15:42 UTC, busma13 commented on packages/scripts/src/helpers/bump/index.ts
> +
`bumpPackagesForAsset` was removed and the functionality was added into `bumpPackages`.

2023-09-18 15:43 UTC, busma13 commented on packages/scripts/test/bump-spec.ts
> +                const path = `${process.cwd()}/asset`;
Done.

2023-09-18 16:37 UTC, busma13 commented on packages/scripts/src/helpers/packages.ts
> +    workspaces = workspaces.filter((space) => space !== '.');
After talking with Jared, we will need to make the test runner asset aware before we can remove the `.` from workspaces.

2023-09-18 21:45 UTC, godber requested changes
Great work!

After some manual review we decided to consider the following changes:

* skip doc generation for assets
* skip initial munging of package.json and tsconfig for assets

I also observed an error when running bump-asset, the top level package.json did not get it's version bumped, only the `asset/package.json` and `asset/asset.json`.

2023-09-19 21:28 UTC, godber requested changes

2023-09-19 21:28 UTC, godber commented on packages/scripts/src/cmds/bump-asset.ts
> +        if (!rootInfo.terascope.asset) {
Move above `syncAll`

2023-09-19 22:55 UTC, godber approved these changes
This looks great, thanks guys

2023-09-20 15:57 UTC, jsnoble requested changes

2023-09-20 15:57 UTC, jsnoble commented on packages/scripts/src/cmds/bump-asset.ts
> +    describe: 'Update an asset to specific version. This should be run in the root of the workspace.',
The describe statement is a bit confusing. This seems to describe the exact same thing as the bump command which will lead to confusion. This statement will show up when using the --help command so this needs to better describe how this is different from bump and when this should be used over bump

2023-09-20 15:57 UTC, jsnoble commented on packages/scripts/src/cmds/bump.ts
> +                description: 'If in an asset repository, bump the package version without updating the asset version',
Which package version does it do?  The top level package.json version usually/should mirror the asset version and should be in sync

2023-09-20 15:57 UTC, jsnoble commented on packages/scripts/src/cmds/bump.ts
> +            signale.warn('bump has detected the root directory is an Asset.');
is there a reason on having two different logging statements here? The first one should not be a warning, it should be at the info level or debug level of logging. Warn should be used if something is off or potentially could be off or run in a dangerous manner

2023-09-20 15:57 UTC, jsnoble commented on packages/scripts/src/helpers/misc.ts
> +                yarn: '>=1.16.0'
since we are changing things, the minimum of yarn if not set should be ` "yarn": ">=1.22.19"`.  We have not updated these things as we should. We have libraries that fail if its less than that

2023-09-20 19:56 UTC, busma13 commented on packages/scripts/src/cmds/bump.ts
> +            signale.warn('bump has detected the root directory is an Asset.');
I've changed this to a single info statement.

2023-09-20 19:57 UTC, busma13 commented on packages/scripts/src/helpers/misc.ts
> +                yarn: '>=1.16.0'
I will also update on line 81.

2023-09-20 20:16 UTC, busma13 commented on packages/scripts/src/cmds/bump.ts
> +                description: 'If in an asset repository, bump the package version without updating the asset version',
I think the trouble is differentiating between packages in the `/packages` directory and package.json files in general. Does this clear it up?
```
description: 'If in an asset repository, bump the version of the specified package(s), but do not update the asset version in \'./package.json\', \'./asset/asset.json\', and \'./asset/package.json\'.',
```

2023-09-20 20:21 UTC, busma13 commented on packages/scripts/src/cmds/bump-asset.ts
> +                description: `Bump release by ${choice}`,
I just copied that straight from bump.ts. Something more like this maybe?
```
      --patch          Bump asset to next patch version 
      --minor          Bump asset to next minor version
      --major          Bump asset to next major version
      --prerelease     Bump asset to next prerelease version
      --prepatch       Bump asset to next prepatch version
      --preminor       Bump asset to next preminor version 
      --premajor       Bump asset to next premajor version
```

2023-09-20 20:23 UTC, godber commented on packages/scripts/src/cmds/bump.ts
> +                description: 'If in an asset repository, bump the package version without updating the asset version',
Start out more concretely, not with an `If`:

```
Bumps a package version and all of the places that package is used in the current repository.
...
```

2023-09-20 20:23 UTC, godber commented on packages/scripts/src/cmds/bump-asset.ts
> +                description: `Bump release by ${choice}`,
That is better.

2023-09-20 20:23 UTC, busma13 commented on packages/scripts/src/cmds/bump-asset.ts
> +    describe: 'Update an asset to specific version. This should be run in the root of the workspace.',
This is what Austin and I came up with. It might be a bit wordy...
```
Update only the asset version.
This is for changes in the asset code. Changes in packages should use the bump command.
This will update the version number in './package.json', './asset/asset.json', and './asset/package.json'.
This should be run in the root of the workspace.
```

2023-09-20 20:38 UTC, busma13 commented on packages/scripts/src/cmds/bump.ts
> +                description: 'If in an asset repository, bump the package version without updating the asset version',
Does this look better?
```
      --skip-asset     Bumps a package version and all of the places that package is used in the current repository.
                       If in an asset repository, do not update the asset version in './package.json', './asset/asset.json', and './asset/package.json'.
```

2023-09-20 20:49 UTC, godber commented on packages/scripts/src/cmds/bump.ts
> +                description: 'If in an asset repository, bump the package version without updating the asset version',
Oh, I was confused, I thought that was the description for `bump` ... I hadn't realized it was for `skip_asset`, so yours is better, just drop the details.

```
description: 'If in an asset repository, bump the version of the specified package(s), but do not update the asset version.',
```

2023-09-20 20:49 UTC, godber commented on packages/scripts/src/cmds/bump.ts
> +                description: 'If in an asset repository, bump the package version without updating the asset version',
Actually, wait, that's not all it does.

2023-09-22 22:54 UTC, godber approved these changes

2023-09-22 23:30 UTC, merged