Add log_level parameter to teraslice job.
terascope/teraslice pull request #3505
Opened 2023-12-18 21:46 UTC by busma13

This PR adds the `log_level` parameter to a teraslice job. 
- Exports `loglevels` from `utils/src/Logger`
- Adds `log_level` to `job-components/src/job-schema`
- Checks `executionConfig` for `log_level` within the `worker-service`. If found, it creates a new child logger with the specified `log_level` and uses that logger to create `Worker` and `ExecutionController` instances. 
- This child logger will be inherited by all other classes that have a logger within `Worker` and `ExecutionController` instances.

2023-12-18 23:06 UTC, godber requested changes
Fix the default problem, and is there a way we could have implemented a test to catch that scenario.

2023-12-18 23:06 UTC, godber commented on packages/job-components/src/job-schemas.ts
> +            default: 'info',
I think this needs to be `undefined` or something, since your conditional in `worker-service.js` tests for existence, it will override the terafoundation config in all cases.

2024-01-02 23:30 UTC, godber approved these changes

2024-01-03 00:12 UTC, godber requested changes
Bump sub package versions and teraslice version to `0.90.0` (both top level and subpackage) and consider the inline suggestion

2024-01-03 00:12 UTC, godber commented on packages/job-components/src/job-schemas.ts
> +                }
Given the check against `logLevels` I think this test for string might be redundant and less useful.  Imaging a user provides a number `5`, then they will be told to use a `string`.  Then they put in the string `noisy`, then it finally tells them the acceptible set of strings.  Maybe the next check should test for string and includes(level).

2024-01-03 00:17 UTC, godber commented
There's not a whole lot of code here, but since it cross cuts packages and schemas and things we might ask for @jsnoble's input.

2024-01-03 14:16 UTC, busma13 commented on packages/job-components/src/job-schemas.ts
> +                }
Good point. I will combine the two checks and just have one error message.

2024-01-03 18:22 UTC, busma13 commented
I added an explanatory comment on each of the constructors that overwrites the log level. I also confirmed that the log_level indicated in the job is written to a log file (all log streams are overwritten with new log level).

2024-01-03 22:16 UTC, godber approved these changes

2024-01-03 23:47 UTC, godber approved these changes

2024-01-03 23:48 UTC, merged