Check for orphaned processes by job_id when starting a job
terascope/teraslice pull request #3508
Opened 2023-12-20 23:35 UTC by busma13

This PR makes the following changes:
- Add check for orphaned resources by job_id before starting job. This applies to Kubernetes clustering only until the force stop option can be improved for native clustering. 
- Add listResourcesForJobId function to execution service.
- Add listResourcesForJobId function to k8s and native cluster backends.

- Improve messaging to user when using force option on the POST /jobs/{job_id}/_stop endpoint
- Remove check for native clustering when using force stop. The force stop options works if using the execution ID tied to the orphaned resource, but does not work when using a job ID if the execution ID has been updated by starting the job again. 
- Update docs for _stop endpoint to show an example using force

2023-12-20 23:47 UTC, godber commented on docs/management-apis/endpoints-json.md
> +}
The response should be valid `json`.

2023-12-20 23:49 UTC, godber commented on docs/management-apis/endpoints-json.md
> +}
Please respond to this with what the stop command returns with (without stop).  We probably need to think about what the key will be.

2023-12-20 23:50 UTC, busma13 commented on docs/management-apis/endpoints-json.md
> +}
```
{
    "status": "completed"
}
```

2023-12-20 23:52 UTC, busma13 commented on docs/management-apis/endpoints-json.md
> +}
Maybe something like this:
```
{
    "msg": "Force stop complete for exId 041a00a9-a474-4355-96aa-03e5ecf9b246",
    "status": "completed"
}
```

2023-12-21 00:05 UTC, godber requested changes
Lets sort out the response and the native method thing before accepting.  Otherwise this looks great.

2023-12-21 00:05 UTC, godber commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +        if (currentResources.length > 0 && clusterType === 'kubernetes') {
I don't really care, but if it does the job, lets use it.  Otherwise I'd rather leave that method stubbed out in `native`.

2023-12-21 00:05 UTC, godber commented on docs/management-apis/endpoints-json.md
> +}
Yeah, that's along the right line, my question is, does precedence for a message like this already exist in the code, if so, what is it?  Lets try and be consistent.

2023-12-21 15:18 UTC, busma13 commented on docs/management-apis/endpoints-json.md
> +}
The JSON APIs return JSON objects or arrays of objects. It looks like `message` is used as a property name on error responses.
```
curl -XPOST localhost:5678/v1/jobs/52861e62-d0b7-46fd-8904-b94422011208/_workers\?add=2
{
    "error": 404,
    "message": "no active execution context was found for ex_id: 620e1385-7944-4986-86e1-662cf44d77ff"
}
```

2023-12-21 15:19 UTC, busma13 commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +        if (currentResources.length > 0 && clusterType === 'kubernetes') {
I was tentative to use it in native because I don't fully understand how jobs are stopped in native. I don't see any issues with my implementation, but I would like @jsnoble to look it over.

2023-12-22 23:26 UTC, godber commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +                curl -XPOST <teraslice host>/v1/ex/${exIdsArr[0]}/_stop?force=true`);
Please remove this option, we don't ever want to encourage people to interact with the `ex` directly, at this point I'd argue for removal of the APIs that enable doing anything other than `GET` on `ex` because it is just going to confuse things.

2023-12-22 23:27 UTC, godber commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +                curl -XPOST <teraslice host>/v1/ex/${exIdsArr[0]}/_stop?force=true`);
```suggestion
```
this ...

2024-01-02 16:20 UTC, godber approved these changes

2024-01-02 16:21 UTC, merged