Change teraslice-cli tests to use temp dir
terascope/teraslice pull request #3509
Opened 2023-12-20 23:58 UTC by sotojn

- Changed tests inside `teraslice-cli` to use temp directories instead of sharing directories
  - This separates state between tests and guarantee directories even when tests are ran in parallel 

This fixes an issue posted here #3494

2023-12-21 00:12 UTC, busma13 requested changes
The new-processor-spec also has directories that are shared. I'm thinking we should take care of that now, before it becomes a problem.

2023-12-22 23:29 UTC, godber submitted a review, later dismissed

2024-01-02 15:24 UTC, sotojn commented
> The new-processor-spec also has directories that are shared. I'm thinking we should take care of that now, before it becomes a problem.

I have updated `new-processor-spec.ts` to also use temp directories. Great feedback!

2024-01-02 16:23 UTC, godber approved these changes

2024-01-02 16:26 UTC, busma13 approved these changes

2024-01-02 16:27 UTC, merged