New ts docker image
terascope/teraslice pull request #3520
Opened 2024-01-10 23:18 UTC by busma13

2024-01-10 23:54 UTC, godber commented
That seemed too easy, what did you do wrong ;)?

2024-01-11 15:25 UTC, busma13 commented on Dockerfile
> +ENV NODE_OPTIONS "--max-old-space-size=2048"
@godber This option needs to be in the final docker image, right? This looks to be related to garbage collection. It was in the `base-docker-image`, but with our current structure it will not be inherited.

2024-01-11 16:38 UTC, godber commented on Dockerfile
> +ENV NODE_OPTIONS "--max-old-space-size=2048"
Yes

2024-01-11 20:37 UTC, godber requested changes
See inline requests

2024-01-11 20:37 UTC, godber commented on Dockerfile
> +     apt-get install -y libcurl4 tini
```suggestion
     apt-get install -y libcurl4 tini && \
       apt-get autoremove -y && \
       apt-get clean -y && \
       rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

You forget to do the cleanup after the `apt update/install`.  So you're leaving at least 20MB in the image:

```
du -sh /var/lib/apt/lists/ /tmp/ /var/tmp/
19M	/var/lib/apt/lists/
2.2M	/tmp/
4.0K	/var/tmp/
```

2024-01-11 20:37 UTC, godber commented on scripts/docker-pkg-fix.js
> +
```suggestion

// We are unsure what this does and it can probably be deleted, looks like something left
// from the migration from Node 10 to Node 12

```

2024-01-11 21:41 UTC, godber approved these changes

2024-01-11 21:43 UTC, merged