Update workflow - drop 16, set default to 18.19.1, add 20.11.1
terascope/teraslice pull request #3551
Opened 2024-02-21 17:27 UTC by busma13

2024-02-28 21:24 UTC, godber requested changes
Fix new linter error.

2024-02-28 21:24 UTC, godber commented on packages/teraslice-client-js/test/assets-spec.ts
>              const contents = fs.readFileSync(testFilePath, 'utf-8');
The linter is complaining about this disabled test, can you convince it not to complain?

2024-02-28 21:44 UTC, busma13 commented on packages/teraslice-client-js/test/assets-spec.ts
>              const contents = fs.readFileSync(testFilePath, 'utf-8');
Done

2024-02-29 00:25 UTC, godber approved these changes

2024-02-29 00:25 UTC, merged