Add and Set Prometheus Metrics
terascope/teraslice pull request #3602
Opened 2024-05-01 23:30 UTC by sotojn

TODO:

- [ ] Move exporter metrics to new internal metrics
- [ ] Potentially add new/useful `cluster_master` metrics that weren't accessible through the api
- [ ]  Add `worker` specific metrics
- [ ] Add `execution` specific metrics

Ref to issue #3600

2024-05-01 23:36 UTC, sotojn commented
After running two jobs on the cluster, stopping one, and pausing one.

This is the result as of right now when you hit the `/metrics` endpoint:

```
# HELP teraslice_cluster_master_controller_workers_active Number of Teraslice workers actively processing slices.
# TYPE teraslice_cluster_master_controller_workers_active gauge
teraslice_cluster_master_controller_workers_active{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",name="ts-dev1",assignment="cluster_master"} 1
teraslice_cluster_master_controller_workers_active{ex_id="9c0ea368-5841-49d4-b886-6550dd0257be",job_id="f93d6350-94ed-422d-9a65-543923defa2f",job_name="test-job-2",name="ts-dev1",assignment="cluster_master"} 0

# HELP teraslice_cluster_master_controller_workers_available Number of Teraslice workers running and waiting for work.
# TYPE teraslice_cluster_master_controller_workers_available gauge
teraslice_cluster_master_controller_workers_available{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_controller_workers_available{ex_id="9c0ea368-5841-49d4-b886-6550dd0257be",job_id="f93d6350-94ed-422d-9a65-543923defa2f",job_name="test-job-2",name="ts-dev1",assignment="cluster_master"} 3

# HELP teraslice_cluster_master_controller_workers_joined Total number of Teraslice workers that have joined the execution controller for this job.
# TYPE teraslice_cluster_master_controller_workers_joined gauge
teraslice_cluster_master_controller_workers_joined{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",name="ts-dev1",assignment="cluster_master"} 1
teraslice_cluster_master_controller_workers_joined{ex_id="9c0ea368-5841-49d4-b886-6550dd0257be",job_id="f93d6350-94ed-422d-9a65-543923defa2f",job_name="test-job-2",name="ts-dev1",assignment="cluster_master"} 3

# HELP teraslice_cluster_master_controller_workers_reconnected Total number of Teraslice workers that have reconnected to the execution controller for this job.
# TYPE teraslice_cluster_master_controller_workers_reconnected gauge
teraslice_cluster_master_controller_workers_reconnected{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_controller_workers_reconnected{ex_id="9c0ea368-5841-49d4-b886-6550dd0257be",job_id="f93d6350-94ed-422d-9a65-543923defa2f",job_name="test-job-2",name="ts-dev1",assignment="cluster_master"} 0

# HELP teraslice_cluster_master_controller_workers_disconnected Total number of Teraslice workers that have disconnected from execution controller for this job.
# TYPE teraslice_cluster_master_controller_workers_disconnected gauge
teraslice_cluster_master_controller_workers_disconnected{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_controller_workers_disconnected{ex_id="9c0ea368-5841-49d4-b886-6550dd0257be",job_id="f93d6350-94ed-422d-9a65-543923defa2f",job_name="test-job-2",name="ts-dev1",assignment="cluster_master"} 0

# HELP teraslice_cluster_master_execution_info Information about Teraslice execution.
# TYPE teraslice_cluster_master_execution_info gauge

# HELP teraslice_cluster_master_controller_slicers_count Number of execution controllers (slicers) running for this execution.
# TYPE teraslice_cluster_master_controller_slicers_count gauge
teraslice_cluster_master_controller_slicers_count{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",name="ts-dev1",assignment="cluster_master"} 1
teraslice_cluster_master_controller_slicers_count{ex_id="9c0ea368-5841-49d4-b886-6550dd0257be",job_id="f93d6350-94ed-422d-9a65-543923defa2f",job_name="test-job-2",name="ts-dev1",assignment="cluster_master"} 1

# HELP teraslice_cluster_master_query_duration_seconds Total time to complete the named query, in seconds.
# TYPE teraslice_cluster_master_query_duration_seconds gauge

# HELP teraslice_cluster_master_execution_cpu_limit CPU core limit for a Teraslice worker container.
# TYPE teraslice_cluster_master_execution_cpu_limit gauge

# HELP teraslice_cluster_master_execution_cpu_request Requested number of CPU cores for a Teraslice worker container.
# TYPE teraslice_cluster_master_execution_cpu_request gauge

# HELP teraslice_cluster_master_execution_memory_limit Memory limit for Teraslice a worker container.
# TYPE teraslice_cluster_master_execution_memory_limit gauge

# HELP teraslice_cluster_master_execution_memory_request Requested amount of memory for a Teraslice worker container.
# TYPE teraslice_cluster_master_execution_memory_request gauge

# HELP teraslice_cluster_master_execution_status Current status of the Teraslice execution.
# TYPE teraslice_cluster_master_execution_status gauge
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="pending",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="scheduling",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="initializing",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="running",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="recovering",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="failing",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="paused",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="stopping",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="completed",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="stopped",name="ts-dev1",assignment="cluster_master"} 1
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="rejected",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="failed",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="a304b828-d7e9-4da9-81a4-806ed478a1ad",job_id="d5e8fa4c-49e3-4d3c-a082-5a27a3a11d87",job_name="test-job-1",status="terminated",name="ts-dev1",assignment="cluster_master"} 0
teraslice_cluster_master_execution_status{ex_id="9c0ea368-5841-49d4-b886-6550dd02 [...]

2024-05-06 20:55 UTC, godber requested changes
Let's make a few changes I've called out here ... if I appear to be misunderstanding something, let me know.

2024-05-06 20:55 UTC, godber commented on docs/development/k8s.md
> +Additionally, there are convenience methods available in the execution, cluster_master, and worker classes for adding metrics. These methods streamline the process by submitting an array of addMetric
These docs are written as if the dev will need to make calls to `add*Metrics()`, but instead, the dev will want to add change the body of these functions to add metrics.  Also these could all be the same function name `addPromMetrics` or `setupPromMetrics` since they are called from different contexts.  I don't know that any documentation is really needed.  Unless I am misunderstanding something.

2024-05-06 20:55 UTC, godber commented on packages/job-components/src/execution-context/worker.ts
> +            // All metrics go inside here
lets add at least one single usecase here.

Also be aware of this discussion of `collect`:

https://github.com/siimon/prom-client?tab=readme-ov-file#custom-metrics

> For metrics based on point-in-time observations (e.g. current memory usage, as opposed to HTTP request durations observed continuously in a histogram), you should provide a collect() function, which will be invoked when Prometheus scrapes your metrics endpoint. collect() can either be synchronous or return a promise. See Gauge below for an example. (Note that you should not update metric values in a setInterval callback; do so in this collect function instead.)

2024-05-07 16:43 UTC, sotojn commented on docs/development/k8s.md
> +Additionally, there are convenience methods available in the execution, cluster_master, and worker classes for adding metrics. These methods streamline the process by submitting an array of addMetric
Renamed all related functions to `setupPromMetrics` and removed unneeded documentation.

2024-05-07 23:27 UTC, godber approved these changes

2024-05-07 23:27 UTC, merged