Move s3 asset_storage settings to teraslice config
terascope/teraslice pull request #3614
Opened 2024-05-14 22:26 UTC by sotojn

This PR makes the following changes:

- TBD

2024-05-15 15:17 UTC, busma13 commented on packages/terafoundation/src/validate-configs.ts
> +        }
Can we refactor so we don't have to delete keys?

2024-05-15 21:03 UTC, jsnoble requested changes

2024-05-15 21:03 UTC, jsnoble commented on packages/teraslice/src/lib/config/schemas/system.ts
> +            const connectionTypesPresent = Object.keys(_sysconfig.terafoundation.connectors);
if _sysconfig is being used it should not have an underscore

2024-05-15 21:03 UTC, jsnoble commented on packages/teraslice/src/lib/config/schemas/system.ts
> +    teraslice: {
since your changing config_schema to what it exports, is there a reason for it to have a teraslice key?

2024-05-17 15:32 UTC, godber requested changes
Fix all the misspelled words.

2024-05-17 16:12 UTC, godber approved these changes

2024-05-17 16:12 UTC, jsnoble approved these changes
LGTM

2024-05-17 16:13 UTC, merged