Add resource cleanup on ex error scenario
terascope/teraslice pull request #3641
Opened 2024-06-05 16:07 UTC by sotojn

This PR makes the following changes:

- Adds resource cleanup on ex error scenario
  - This adds a functionality to the shutdown function on the `ex controller` that checks to see if shutdown was caused by a specific error. Then proceeds to tell the `cluster master` to cleanup the resources.
  - #2673

2024-06-05 21:45 UTC, godber requested changes

2024-06-05 21:45 UTC, godber commented on packages/teraslice-messaging/src/cluster-master/server.ts
> +    onExecutionError(fn: (clientId: string, error?: core.ResponseError) => void): void {
During review we concluded that onExecutionError could be eliminated and we can use onExecutionFinished with an error parameter instead.

2024-06-05 21:45 UTC, godber commented on packages/teraslice/src/lib/workers/execution-controller/index.ts
> +                this.client.sendExecutionError(shutdownError.message);
We need an await here.

2024-06-05 23:30 UTC, sotojn commented on packages/teraslice/src/lib/workers/worker/index.ts
> +    async shutdown(event?: string, shutdownError?: Error, block?: boolean) {
This is because of a lint error where default params must be at the end.

2024-06-14 17:50 UTC, busma13 requested changes

2024-06-14 17:50 UTC, busma13 commented on packages/teraslice/src/lib/cluster/services/execution.ts
> +
This function is no longer used.

2024-06-14 17:50 UTC, busma13 commented on packages/teraslice/src/lib/workers/execution-controller/index.ts
> +                this.logger.error('sent request to cluster_master to cleanup job resources.');
Should this be an `error` level log? Has the error been logged already? If so maybe this could be a `warn` level log. If not we should tell them what the error was.

2024-06-17 17:29 UTC, busma13 commented on packages/teraslice/src/lib/workers/execution-controller/index.ts
> +                this.logger.error('sent request to cluster_master to cleanup job resources.');
The error is logged prior to this log. I changed this to a `warn`

2024-06-17 17:32 UTC, busma13 approved these changes

2024-06-17 21:03 UTC, godber approved these changes
After the changes this looks good.

2024-06-17 21:04 UTC, godber commented
Lets bump the patch level now.  We'll release after this.

2024-06-17 21:15 UTC, godber approved these changes
approved version bumps

2024-06-17 21:41 UTC, merged