Add labels to docker image
terascope/teraslice pull request #3677
Opened 2024-07-05 15:48 UTC by busma13

2024-07-09 21:52 UTC, godber commented
When this PR is ready for review, lets:

* Have @mkhpalm review it
*Bump the teraslice version to `v2.1.0`.

2024-07-10 17:43 UTC, mkhpalm commented
I've reviewed the labels and they look good for opencontainers image-spec

2024-07-10 20:09 UTC, godber commented
@busma13 do you have an image built from this branch?  Can you run the following command on the IMAGE and paste the output here?

```
docker inspect IMAGE | jq '.[0].Config.Labels'
```

2024-07-10 20:54 UTC, busma13 commented
```
➜  teraslice git:(add-labels-to-docker-image) docker inspect terascope/teraslice:latest-nodev18.19.1 | jq '.[0].Config.Labels'
{
  "org.opencontainers.image.created": "2024-07-10T20:51:55.958Z",
  "org.opencontainers.image.documentation": "https://terascope.github.io/teraslice/docs/overview",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.revision": "someHashValue",
  "org.opencontainers.image.source": "https://github.com/terascope/teraslice",
  "org.opencontainers.image.title": "Teraslice",
  "org.opencontainers.image.url": "https://terascope.github.io/teraslice",
  "org.opencontainers.image.vendor": "Terascope",
  "org.opencontainers.image.version": "2.0.1"
}
```

2024-07-10 21:01 UTC, godber commented
So `"org.opencontainers.image.revision": "someHashValue",` is due to this being a local test, right?

2024-07-10 21:31 UTC, godber requested changes
I'll approve this after you bump it to `v2.1.0`

2024-07-10 21:32 UTC, busma13 commented
> So `"org.opencontainers.image.revision": "someHashValue",` is due to this being a local test, right?

Correct. I set a local env var - export GITHUB_SHA=someHashValue

2024-07-11 01:46 UTC, godber approved these changes

2024-07-11 01:46 UTC, merged