Add --diff option teraslice-cli
terascope/teraslice pull request #3710
Opened 2024-08-05 18:46 UTC by sotojn

This PR makes the following changes: 

- Adds `--diff` option to `teraslice cli view` that will compare the local `json` job file with what teraslice has on the state cluster
- Bumps `teraslice-cli` from `v2.1.0` to `v2.2.0`

Ref to issue #3694

2024-08-06 17:36 UTC, busma13 requested changes

2024-08-06 17:36 UTC, busma13 commented on packages/teraslice-cli/src/helpers/jobs.ts
> +            localJobConfigs[formatedJobConfig.job_id as string] = formatedJobConfig;
```suggestion
            const formattedJobConfig = this.formatJobConfig(jobConfig);
            localJobConfigs[formatedJobConfig.job_id as string] = formattedJobConfig;
```

2024-08-06 17:36 UTC, busma13 commented on packages/teraslice-cli/src/helpers/yargs-options.ts
> +            describe: 'Shows diff on a job in a cluster and a job file',
Maybe `Shows diff between a job...`?

2024-08-06 22:30 UTC, busma13 approved these changes
Looks good

2024-08-06 22:31 UTC, sotojn commented
Here is an example on how this option looks. In the json file I change the amount of workers from 1 to 2 and run:

`earl tjm view test-job.json --diff`

Output:
```diff
  {
   "_context": "job",
   "_created": "2024-08-01T22:34:50.219Z",
-   "_updated": "2024-08-06T16:03:58.734Z",
+   "_updated": "2024-08-06T16:03:58.777Z",
    "assets": [
      "standard",
      "file"
    ],
    "job_id": "48e59745-ed75-4060-998e-002262abefc3",
    "lifecycle": "once",
    "name": "data-to-s3",
    "operations": [
      {
        "_op": "data_generator",
        "size": 100000
      },
      {
        "_op": "s3_exporter",
        "format": "ldjson",
        "path": "josephorigin"
      }
    ],
-   "workers": 1
+   "workers": 2
  }
```
```
--------
job: data-to-s3
id: 48e59745-ed75-4060-998e-002262abefc3
cluster: http://localhost:5678
--------
```
It does appear that updated seems slightly off all the time and maybe we shouldn't compare it?

2024-08-06 22:35 UTC, busma13 commented
> It does appear that updated seems slightly off all the time and maybe we shouldn't compare it?

I think it could be helpful to know that `_update` will be different between the two records.

2024-08-07 14:51 UTC, sotojn commented
> > It does appear that updated seems slightly off all the time and maybe we shouldn't compare it?
> 
> I think it could be helpful to know that `_update` will be different between the two records.

Should this be some sort of warning like, "_update field is subject to being slightly different from job file, to whats on the job record in the state cluster". Or should I just ignore this comparison entirely?

2024-08-07 14:59 UTC, busma13 commented
My feeling is that it's fine how it is now and a warning isn't necessary. But maybe it would be better to not compare `_update` if only the milliseconds are different.

2024-08-07 16:53 UTC, ciorg commented
If there is no difference could it out put something like - no difference between the configs instead of printing the whole config, not a big deal it's a pain to do so?   

Also, what color applies to what config? Green is the local file and red is the cluster config?  Maybe something to let people know what applies to what.

So far as the `update` difference, which for some reason is always different than the cluster value, at least on all the jobs I've looked at so far.   ( I'm not sure how the update is calculated, but it seems like that value should be the same for both?  Or maybe it shouldn't  even have millisecond precision?  But that is a different issue)   

It is interesting to know when the job was last updated, but if the diff is 100 ms it doesn't really tell me anything useful.  So maybe if there's a way to hide that diff unless it's at least a few min difference that would be better.

2024-08-08 16:52 UTC, sotojn commented
I've updated the behavior to include what is being compared to what. I also added logic around the "_updated" field to only display a diff if the time difference is greater than a minute. 

Results if "_updated field is less than 1 minute":
Command: `earl tjm view  data-to-s3.json  --diff`
```diff
  {
    "assets": [
      "standard",
      "file"
    ],
    "job_id": "48e59745-ed75-4060-998e-002262abefc3",
    "lifecycle": "once",
    "name": "data-to-s3",
    "operations": [
      {
        "_op": "data_generator",
        "size": 100000
      },
      {
        "_op": "s3_exporter",
        "format": "ldjson",
        "path": "josephorigin"
      }
    ],
-   "workers": 1   <--- state cluster value
+   "workers": 2   <--- local job file value
  }
```
```
--------
job: data-to-s3
id: 48e59745-ed75-4060-998e-002262abefc3
cluster: http://domain123
--------
```

Results if "_updated field is greater than 1 minute":
Command: `earl tjm view  data-to-s3.json  --diff`
```diff
  {
-   "_updated": "2024-08-06T16:03:58.734Z",   <--- state cluster value
+   "_updated": "2024-07-06T16:03:58.777Z",   <--- local job file value
    "assets": [
      "standard",
      "file"
    ],
    "job_id": "48e59745-ed75-4060-998e-002262abefc3",
    "lifecycle": "once",
    "name": "data-to-s3",
    "operations": [
      {
        "_op": "data_generator",
        "size": 100000
      },
      {
        "_op": "s3_exporter",
        "format": "ldjson",
        "path": "josephorigin"
      }
    ],
-   "workers": 1   <--- state cluster value
+   "workers": 2   <--- local job file value
  }
```
```
--------
job: data-to-s3
id: 48e59745-ed75-4060-998e-002262abefc3
cluster: http://domain123
--------
```

2024-08-08 20:41 UTC, ciorg approved these changes
LGTM

2024-08-08 22:12 UTC, busma13 approved these changes
Looks good.

2024-08-08 22:14 UTC, merged