Add ability to soft delete a job
terascope/teraslice pull request #3711
Opened 2024-08-06 14:11 UTC by busma13

2024-08-08 22:32 UTC, busma13 commented
```
➜  jobs-local git:(main) ✗ curl -XDELETE localhost:5678/jobs/65c01465-80be-4932-9c12-3a640e082c4b
{
    "name": "peter-datagen-to-kafka",
    "lifecycle": "persistent",
    "workers": 1,
    "assets": [
        "standard",
        "kafka"
    ],
    "operations": [
        {
            "_op": "data_generator",
            "size": 5000
        },
        {
            "_op": "kafka_sender",
            "topic": "rand-p-json-v1",
            "size": 5000
        }
    ],
    "job_id": "65c01465-80be-4932-9c12-3a640e082c4b",
    "_context": "job",
    "_created": "2024-08-08T22:22:26.519Z",
    "_updated": "2024-08-08T22:31:24.752Z",
    "_deleted": true,
    "_deleted_on": "2024-08-08T22:31:24.750Z",
    "active": false
}
```

2024-08-08 22:49 UTC, busma13 commented
```
➜  teraslice git:(job-deletion) earl tjm delete peter-datagen-to-kafka.json
✔ Delete job 23b72801-857f-4457-b947-9ca8c59c5794 on http://localhost:5678 … yes
> peter-datagen-to-kafka has been deleted
--------
job: peter-datagen-to-es
id: 7636e71b-eda8-4a8d-8069-bc5201985271
cluster: http://localhost:5678
--------

➜  teraslice git:(job-deletion) earl jobs delete local 7636e71b-eda8-4a8d-8069-bc5201985271
✔ Delete job 7636e71b-eda8-4a8d-8069-bc5201985271 on local … yes
> peter-datagen-to-es has been deleted
--------
job: peter-datagen-to-kafka
id: 23b72801-857f-4457-b947-9ca8c59c5794
cluster: http://localhost:5678
--------
```

2024-08-08 22:58 UTC, busma13 commented
```
➜  teraslice git:(job-deletion) ✗ earl jobs list local
 job_id                                name                 lifecycle   slicers  workers  _created                  _updated
 21963e57-4fa0-4cae-a1b9-304c2305f8bc  peter-datagen-to-s3  persistent           1        2024-08-08T22:51:40.220Z  2024-08-08T22:51:40.220Z

➜  teraslice git:(job-deletion) ✗ earl jobs list local --deleted only
 job_id                                name                    lifecycle   slicers  workers  _created                  _updated                  _deleted_on
 7636e71b-eda8-4a8d-8069-bc5201985271  peter-datagen-to-es     persistent           1        2024-08-08T22:39:16.225Z  2024-08-08T22:48:40.471Z  2024-08-08T22:48:40.458Z
 23b72801-857f-4457-b947-9ca8c59c5794  peter-datagen-to-kafka  persistent           1        2024-08-08T22:34:55.284Z  2024-08-08T22:36:03.203Z  2024-08-08T22:36:03.201Z

➜  teraslice git:(job-deletion) ✗ earl jobs list local --deleted include
 job_id                                name                    lifecycle   slicers  workers  _created                  _updated                  _deleted_on
 21963e57-4fa0-4cae-a1b9-304c2305f8bc  peter-datagen-to-s3     persistent           1        2024-08-08T22:51:40.220Z  2024-08-08T22:51:40.220Z
 7636e71b-eda8-4a8d-8069-bc5201985271  peter-datagen-to-es     persistent           1        2024-08-08T22:39:16.225Z  2024-08-08T22:48:40.471Z  2024-08-08T22:48:40.458Z
 23b72801-857f-4457-b947-9ca8c59c5794  peter-datagen-to-kafka  persistent           1        2024-08-08T22:34:55.284Z  2024-08-08T22:36:03.203Z  2024-08-08T22:36:03.201Z
```

```
➜  teraslice git:(job-deletion) ✗ earl ex list local
 name                 lifecycle   slicers  workers  _status  ex_id                                 job_id                                _created                  _updated
 peter-datagen-to-s3  persistent  1        1        running  abc20261-0baf-4e62-8432-3b57b00aae21  21963e57-4fa0-4cae-a1b9-304c2305f8bc  2024-08-08T22:54:40.986Z  2024-08-08T22:54:50.922Z

➜  teraslice git:(job-deletion) ✗ earl ex list local --deleted only
 name                 lifecycle   slicers  workers  _status  ex_id                                 job_id                                _created                  _updated                  _deleted_on
 peter-datagen-to-es  persistent  1        1        stopped  92a2c02b-51a3-4643-8b42-02bb0369a3eb  7636e71b-eda8-4a8d-8069-bc5201985271  2024-08-08T22:39:30.672Z  2024-08-08T22:48:40.460Z  2024-08-08T22:48:40.460Z

➜  teraslice git:(job-deletion) ✗ earl ex list local --deleted include
 name                 lifecycle   slicers  workers  _status  ex_id                                 job_id                                _created                  _updated                  _deleted_on
 peter-datagen-to-s3  persistent  1        1        running  abc20261-0baf-4e62-8432-3b57b00aae21  21963e57-4fa0-4cae-a1b9-304c2305f8bc  2024-08-08T22:54:40.986Z  2024-08-08T22:54:50.922Z
 peter-datagen-to-es  persistent  1        1        stopped  92a2c02b-51a3-4643-8b42-02bb0369a3eb  7636e71b-eda8-4a8d-8069-bc5201985271  2024-08-08T22:39:30.672Z  2024-08-08T22:48:40.460Z  2024-08-08T22:48:40.460Z
```

2024-08-10 00:07 UTC, ciorg commented on packages/teraslice-client-js/src/jobs.ts
> -function _parseListOptions(options?: Teraslice.JobListStatusQuery): Teraslice.JobSearchParams {
Does this mean we don't support legacy anymore?

2024-08-10 00:07 UTC, ciorg commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +            // FIXME: we could alternatively throw an error here and make the user force remove
I think it's good how it is, to automatically remove the resources

2024-08-19 14:58 UTC, busma13 commented on docs/management-apis/endpoints-txt.md
> +- `deleted: string = [exclude|include|only]`
I think we would also want to change `exclude` to `false` if we go this route.

2024-08-19 15:02 UTC, busma13 commented on packages/teraslice-cli/src/cmds/jobs/delete.ts
> +    describe: 'Delete jobs from the teraslice cluster. Jobs must be stopped.',
Yes, any terminal state.

2024-08-19 17:47 UTC, busma13 commented on packages/teraslice-cli/src/helpers/jobs.ts
> +        if (this.jobs.length === 1 && this.config.args.yes !== true) {
Yeah, this is wrong.

2024-08-23 15:56 UTC, jsnoble requested changes

2024-08-23 15:56 UTC, jsnoble commented on docs/management-apis/endpoints-json.md
> +## DELETE /v1/jobs/&#123;jobId&#125;
You might want to escape ```&#123;``` or change  how its presented as it does not make any sense like this

2024-08-23 15:56 UTC, jsnoble commented on docs/packages/teraslice-cli/overview.md
> +teraslice-cli jobs list local --active true
I am a little confused by this, ```teraslice-cli jobs list local --active true```. The last part of it with ```true``` does not make much sense, usually there would be a word or flag that represents what this is doing, and internally that would be converted to a boolean. I don't know if this is a mistake or on purpose, but in my experince that is not a great command parameter

2024-08-23 15:56 UTC, jsnoble commented on packages/teraslice-cli/src/helpers/jobs.ts
> +            const { _action, clusterAlias, clusterUrl } = this.config.args;
a variable that starts with a _ denotes that it is either not used at all (which is the main meaning), or a hidden variable that is not supposed to be used normally and its dangerous to rely on it as its an internal thing outside normal api operations, that it is a hack. Another use would be for some hidden metadata that is not really meant for users to deal with. Please rename this

2024-08-23 18:00 UTC, busma13 commented on docs/management-apis/endpoints-json.md
> +## DELETE /v1/jobs/&#123;jobId&#125;
I am able to just escape the curly braces so it is readable in the repo and parses correctly on the website. I believe this didn't work in v2 of docusaurus, but it does in v3. I should have tried it again when I finished the upgrade.

2024-09-03 20:36 UTC, busma13 commented on docs/packages/teraslice-cli/overview.md
> +teraslice-cli tjm delete JOB1.json JOB2.JSON
fix capitalization

2024-09-03 21:54 UTC, busma13 commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +        let currentResources = await this.executionService.listResourcesForJobId(jobId);
add comment about k8s resource

2024-09-03 21:54 UTC, busma13 commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +        }
Don't soft delete executions.

2024-09-03 21:54 UTC, busma13 commented on packages/teraslice/src/lib/cluster/services/jobs.ts
> +    async getAllExecutions(
delete me

2024-09-03 21:54 UTC, busma13 commented on packages/teraslice/src/lib/storage/execution.ts
> +    async softDelete(exId: string) {
remove me

2024-09-04 19:54 UTC, busma13 commented on docs/management-apis/endpoints-txt.md
> +- `deleted: string = [exclude|include|only]`
We decided to simplify things and make it true|false

2024-09-05 15:35 UTC, busma13 commented on packages/teraslice-client-js/src/jobs.ts
> -function _parseListOptions(options?: Teraslice.JobListStatusQuery): Teraslice.JobSearchParams {
The GET /jobs endpoint stopped parsing the status option in 2016, and is completely ignored. This makes sense, since status is now only associated with executions, not jobs.

2024-09-05 21:05 UTC, godber requested changes
Please, at the very least make the requested doc change.  The e2e changes are optional.

2024-09-05 21:05 UTC, godber commented on e2e/test/cases/cluster/api-spec.ts
> +        await expect(terasliceHarness.teraslice.jobs.delete(`/jobs/${jobId}`)).resolves.toMatchObject(deletedJobProperties);
At this point, the job should not show up in `/txt/jobs`, if there's an easy way to test that, it might be worth doing.

You can test any of the scenarios that being deleted causes, like no updating or starting.

2024-09-05 21:05 UTC, godber commented on docs/management-apis/endpoints-json.md
> +Issues a delete command, deleting the job and all related execution contexts. Any orphaned K8s resources associated with the job will also be deleted. The job must have a terminal status to be delete
Please extend this with the consequences of deleting a job:

A delete job cannot be updated ....

2024-09-06 16:16 UTC, godber approved these changes

2024-09-06 17:49 UTC, ciorg commented
LGTM

2024-09-06 21:27 UTC, jsnoble approved these changes
LGTM

2024-09-06 21:28 UTC, merged