Add readiness probe to k8s job
terascope/teraslice pull request #3721
Opened 2024-08-16 17:06 UTC by sotojn

TBD

Ref to issue #3720

2024-08-21 21:51 UTC, busma13 approved these changes
This looks good

2024-08-21 21:53 UTC, godber requested changes
Don't change the original `kubernetes` backend.

2024-08-21 21:53 UTC, godber commented on packages/teraslice-messaging/src/execution-controller/server.ts
> +        this.executionReady = false;
This is a change that will impact all backend types and could be problematic.  I find it strange that this wasn't set before, how is this used in other `native` and `kubernetes` backend types?

2024-08-21 21:53 UTC, godber commented on packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/index.ts
> +        /// Wait for ex readiness probe to return 'Ready'
Why are we changing the `kubernetes` backend?

2024-08-22 20:33 UTC, godber commented on packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/jobs/execution_controller.hbs
> +                        "timeoutSeconds": 5,
```suggestion
                        "initialDelaySeconds": 3,
                        "periodSeconds": 10,
                        "timeoutSeconds": 1,
```

I don't think we should extend `timeoutSeconds` from the default.  I've shortened `initialDelaySeconds`, if that doesn't work for some reason, you can put it back.  We can leave `periodSeconds` as it is.

2024-08-22 20:34 UTC, godber commented on packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/jobs/execution_controller.hbs
> +                        "timeoutSeconds": 5,
Was there any reason you made `timeoutSeconds` longer?  Did you experiment with a shorter `initialDelaySeconds` at all?

2024-08-22 20:41 UTC, sotojn commented on packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetesV2/jobs/execution_controller.hbs
> +                        "timeoutSeconds": 5,
No I have not. It was more of ensuring that the probe doesn't fail after the retry amount exceeded. But maybe I could have increased the `failureThreshold` instead of adding to the delay. Giving the probe an opportunity to return a Ready status a lot sooner.

2024-08-22 21:56 UTC, godber approved these changes

2024-08-22 21:56 UTC, merged