Add execution info query to job api
terascope/teraslice pull request #3792
Opened 2024-10-10 18:52 UTC by sotojn

TBD

2024-10-16 23:32 UTC, sotojn commented on docs/management-apis/endpoints-json.md
> +## test /stuff
We need to remove this.
```suggestion

```

2024-10-17 00:22 UTC, godber reviewed
Consider the invalid field case

2024-10-17 00:22 UTC, godber commented on packages/teraslice/src/lib/cluster/services/api.ts
> +            typeof ex === 'string'
What happens if we specify `ex=dingo`?

2024-10-17 00:22 UTC, godber commented on packages/teraslice/src/lib/cluster/services/api.ts
> +            typeof ex === 'string'
Can/should we reject the query if the field is not valid?

2024-10-17 15:31 UTC, sotojn commented on packages/teraslice/src/lib/cluster/services/api.ts
> +            typeof ex === 'string'
I've tested this yesterday and if you do `ex=dingo` it will return an empty execution object.
```
ex: {}
``` 
If you were to include a mix between valid and invalid fields such as `ex=_status,dingo,assets` the result would pull up all valid fields and ignore invalid fields.
```
ex: {
    _status: "running",
    assets: [
        abc123blahimahash
    ]
}
```

2024-10-17 15:46 UTC, sotojn commented on packages/teraslice/src/lib/cluster/services/api.ts
> +            typeof ex === 'string'
This behavior is carried over on how elasticsearch requests handle invalid fields, which in this case just ignores them.

2024-10-17 18:19 UTC, godber commented on packages/teraslice/src/lib/cluster/services/api.ts
> +            typeof ex === 'string'
Ok, that sounds appropriate.

2024-10-17 22:27 UTC, godber requested changes
you've left garbage around in here.

2024-10-17 22:27 UTC, godber commented on docs/management-apis/endpoints-json.md
> +## test /stuff
```suggestion
```

Not sure why this isn't deleted.  Lets try again

2024-10-17 23:00 UTC, godber approved these changes

2024-10-17 23:01 UTC, merged

2024-10-22 21:54 UTC, godber commented
This PR was for issue: https://github.com/terascope/teraslice/issues/3770