Asset load dependency check
terascope/teraslice pull request #3822
Opened 2024-11-12 20:39 UTC by busma13

2024-11-12 21:59 UTC, busma13 commented on packages/teraslice/src/lib/utils/file_utils.ts
> +    };
We probably want to think hard about what we name this and if it should be an object that holds several versions or not.

2024-11-13 23:53 UTC, godber commented on packages/teraslice/src/lib/utils/file_utils.ts
> +    };
I'd say it's unavoidable since you can't know what breaking changes can be implemented in the future.

As long as this value won't need to be validated by convict that nested value looks OK.  But every time I've tried to nest something like that I've gotten hung up when it goes through convict for validation (I think that was the issue).  If we wanted to play it dumb and safe we could just do this: `"minimum-teraslice-version"`.

2024-11-13 23:58 UTC, godber commented
We really shouldn't be adding large binary files to the repo, especially one this large.  At this point, since you've pushed the branch it's already there.  So leave it.

2024-11-14 00:19 UTC, godber requested changes
Lets discuss this in the morning.

2024-11-14 00:19 UTC, godber commented on packages/teraslice/src/lib/utils/file_utils.ts
> +        if (semver.gt(metadata.minimum_versions.teraslice, terasliceVersion)) {
What happens if the asset contains:

```
    minimum_versions: {
    };
```

So `metadata.minimum_versions.teraslice` is undefined?

Maybe we should just go back to a single property, no nested thing.

2024-11-14 15:25 UTC, busma13 commented on packages/teraslice/src/lib/utils/file_utils.ts
> +        if (semver.gt(metadata.minimum_versions.teraslice, terasliceVersion)) {
Yeah this would have thrown an error because semver.gt() won't take undefined as a parameter.

2024-11-14 15:28 UTC, busma13 commented
I think the single property makes more sense. Any other compatibility check can have it's own top level property. This also gives me a chance to use a smaller asset.

2024-11-14 22:01 UTC, godber approved these changes

2024-11-14 22:01 UTC, merged