Op asset specificity
terascope/teraslice pull request #3841
Opened 2024-11-25 13:52 UTC by jsnoble

- jobs will throw if there are name collisions and the op name has no asset identifier
- can now specify op/reader/apis names as `op-name@assetName:v1.4.0` or  `op-name@assetName`

2024-11-27 19:06 UTC, godber commented
When you're back Jared, you'll need to rebase this and bump the version to 2.10.0 since we did a 2.9.0 release today.

2024-12-03 17:10 UTC, jsnoble commented
To test this out, setup a running teraslice instance, and use teraslice-cli to upload assets

```
teraslice-cli assets deploy localhost terascope/elasticsearch-assets@v4.0.2
teraslice-cli assets deploy localhost terascope/elasticsearch-assets@v4.0.5
```

Sample Job that should fail because we don't know which asset to use for the op, please adjust index and any other settings for your setup
```
{
    "name": "test",
    "lifecycle": "once",
    "workers": 1,
    "analytics": true,
    "assets": [
        "elasticsearch:4.0.2",
        "elasticsearch:4.0.5"
    ],
    "operations": [
        {
            "_op": "elasticsearch_reader",
            "index": "ts_test_example-1000",
            "size": 10000,
            "date_field_name": "created",
            "preserve_id": true
        },
        {
            "_op": "elasticsearch_bulk",
            "index": "op_asset_version_test",
            "preserve_id": true,
            "size": 10000
        }
    ]
}
```

Sample job that should pass, please make the same updates to index and any other changes neccessary
```
{
    "name": "test",
    "lifecycle": "once",
    "workers": 1,
    "analytics": true,
    "assets": [
        "elasticsearch:4.0.2",
        "elasticsearch:4.0.5"
    ],
    "operations": [
        {
            "_op": "elasticsearch_reader@elasticsearch:4.0.2",
            "index": "ts_test_example-1000",
            "size": 10000,
            "date_field_name": "created",
            "preserve_id": true
        },
        {
            "_op": "elasticsearch_bulk@elasticsearch:4.0.5",
            "index": "op_asset_version_test",
            "preserve_id": true,
            "size": 10000
        }
    ]
}
```

2024-12-03 21:27 UTC, ciorg commented
Here's my test

job config:
```
"assets": [
        "common_processors:0.16.0",
        "standard:1.2.0"
    ],
    "operations": [
        {
            "_op": "data_generator",
            "size": 1
        },
        {
            "_op": "filter",
            "field": "ip",
            "value": "0.0.0.0"
        },
        {
            "_op": "noop"
        }
    ]
```

When I tried to run with this config I got  the error `Multiple assets containing the same processor name _op: "filter", please specify which specific asset to use on its name`.   Added `1filter@common_processors:0.16.0` and the job updated and ran.

I also tried the job will multiple `filter` ops using both assets and it worked as expected.  I also tried just adding the asset name with no version, but it requires the version, which makes sense.

2024-12-06 21:33 UTC, jsnoble commented
Example of real job that can work with the elasticsearch-assets
```json
{
    "name": "test",
    "lifecycle": "once",
    "workers": 1,
    "analytics": true,
    "assets": [
        "elasticsearch:4.0.2",
        "elasticsearch:4.0.5"
    ],
    "apis": [
        {
            "_name": "elasticsearch_sender_api@elasticsearch:4.0.5",
            "index": "op_asset_version_test",
            "preserve_id": true,
            "size": 10000
        },
        {
            "_name": "elasticsearch_reader_api@elasticsearch:4.0.2",
            "index": "ts_test_example-1000",
            "size": 10000,
            "date_field_name": "created",
            "preserve_id": true
        }
    ],
    "operations": [
        {
            "_op": "elasticsearch_reader@elasticsearch:4.0.2",
            "api_name": "elasticsearch_reader_api@elasticsearch:4.0.2",
            "index": "ts_test_example-1000",
            "size": 10000,
            "date_field_name": "created",
            "preserve_id": true
        },
        {
            "_op": "elasticsearch_bulk@elasticsearch:4.0.5",
            "api_name": "elasticsearch_sender_api@elasticsearch:4.0.5",
            "index": "op_asset_version_test",
            "preserve_id": true,
            "size": 10000
        }
    ]
}
```

2024-12-09 22:45 UTC, godber requested changes
Consider some of my comments inline, I think I found the parseName tests, I didn't expect them included inside another specfile.

Please try and document the extent of the changes you have made in the documentation.  What all is now possible?  What scenarios are prohibited?  What are tags?

2024-12-09 22:45 UTC, godber commented on packages/job-components/src/operation-loader/utils.ts
This file looks like it is easily unit testable.  I don't see any unit tests, perhaps I am overlooking them.

2024-12-09 22:45 UTC, godber commented on packages/job-components/src/operation-loader/utils.ts
> +    return id.length === 40;
This logic results in any `id` length of 40 being treated as an assetHash right?  Can't this be accidentally triggered?  In this case what is `id`?  Is it `elasticsearch` or `elasticsearch:v1.0.1`.  Is there a more concrete way for us  to ensure this string is really a hash?

2024-12-09 22:45 UTC, godber commented on packages/job-components/src/operation-loader/loader.ts
> +    async loadProcessor(name: string, assetIds?: string[]): Promise<ProcessorModule> {
Adding a tsdoc comment that describes these functions might be useful.

2024-12-09 22:45 UTC, godber commented on packages/job-components/src/job-validator.ts
> +                // revert name back to original
It would be useful to know why we revert back to original name.  What things require it?

2024-12-09 22:45 UTC, godber commented on packages/job-components/test/operation-loader-spec.ts
> +        const assetHash1 = 'op_asset_v1.0.0';
Elsewhere we expect asset hashes to be 40 characters in length, is that condition not necessary in this context for some reason?  Perhaps the variable name is just confusing, maybe you mean something more like `assetIdentifier1`.

2024-12-10 22:03 UTC, busma13 commented
I was testing this and it looks like using a plain `apiName` with no `@` or using `apiName:tag` is now broken. I think `adjustNamesByMapping()` is using an undefined `assetIdentifier` when trying to look up the asset hash.

2025-01-06 21:04 UTC, busma13 approved these changes
Looks good. There were just a few typos, etc I noticed.

2025-01-06 21:07 UTC, jsnoble commented on docs/jobs/configuration.md
> +<!--Example with multiple apis->
this is following that pattern in the docs above of how to list code, not sure, just following current doc patterns

2025-01-06 21:07 UTC, jsnoble commented on e2e/test/cases/assets/simple-spec.ts
> +        /*
same as above

2025-01-06 21:15 UTC, jsnoble commented on packages/job-components/src/job-validator.ts
> +                // revert name back to original
we have to revert back due to issues with backwards compatibility because in the assets in checks with a `===` for exact matching of names for post schema validation checks that create api names

2025-01-06 21:31 UTC, merged